services:
  - type: web
    name: steam-wishlist-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: cd backend && gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: steam-wishlist-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"

databases:
  - name: steam-wishlist-db
    plan: free
    databaseName: steam_wishlist
    user: steam_user
