services:
  - type: web
    name: steam-wishlist-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python backend/manage.py collectstatic --noinput
      python backend/manage.py migrate
    startCommand: gunicorn backend.core.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: TELEGRAM_BOT_TOKEN
        value: "your_bot_token_here"
      - key: TELEGRAM_BOT_USERNAME  
        value: "SteamWishlistNotifierBot"

databases:
  - name: steam-wishlist-db
    plan: free
    databaseName: steam_wishlist
    user: steam_user
